### ISSUE TITLE
Views won't render out of the box

### ISSUE THREAD

**Issue by thermaldonkey** [CTA/cta-template#1]
After initial installation of gems and project creation, I ran a scaffold generator to create a resource with views. The views were in HAML, but running the server in development wouldn't render anything until I made my own ERB views.

**Comment by hahnzilla** [comment]
What version of rails are you using? Because I have only verified this template working with 3.2.*

**Comment by thermaldonkey** [comment]
Ah! That would make sense. I changed my default Rails version down from 4.0.0.rc2 and the views rendered just fine. Thanks for that!

**Comment by hahnzilla** [comment]
Github Wi-Five! I'll add in a comment about what versions of rails are currently supported.
